project:
  type: website
  output-dir: docs

website:
  title: "Brandon J. Nelson"
  navbar:
    right:
      - about.qmd
      - publications.qmd
      - presentations.qmd
      - icon: github
        href: https://github.com/bnel1201
      - icon: twitter
        href: https://twitter.com/brandon_jnelson
      - icon: linkedin
        href: https://www.linkedin.com/in/brandonj-nelson
format:
  html:
    theme: cosmo
    css: styles.css



